# -*- coding: utf-8 -*-

"""
/***************************************************************************
 MinimalisticMBTilesGenerator
                                 A QGIS plugin
 Generate XYZ tiles (MBTiles) only around the features of a given vector layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-06-28
        copyright            : (C) 2021 by Francesco Frassinelli/Norsk institutt for naturforskning
        email                : francesco.frassinelli@nina.no
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Francesco Frassinelli/Norsk institutt for naturforskning'
__date__ = '2021-06-28'
__copyright__ = '(C) 2021 by Francesco Frassinelli/Norsk institutt for naturforskning'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from .minimalistic_mbtiles_generator_provider import MinimalisticMBTilesGeneratorProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class MinimalisticMBTilesGeneratorPlugin(object):

    def __init__(self):
        self.provider = None

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = MinimalisticMBTilesGeneratorProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
